include(${CMAKE_CURRENT_LIST_DIR}/GeneralFeatures.cmake)

set(THIS_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR})
if(WIN32)
    include(${CMAKE_CURRENT_LIST_DIR}/WinFeatures.cmake)
    
    if(BUILD_TYPE STREQUAL "Release")
        set(LibconfigLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Release/libconfig++.lib )
        set(LibconfigDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Release/libconfig++.dll )
    else()
        set(LibconfigLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Debug/libconfig++.lib )
        set(LibconfigDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Debug/libconfig++.dll )
    endif()

    set(CurlLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/win/x64/libcurl.lib )
    set(CurlDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/win/x64/libcurl.dll )
    set(SqliteLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/sqlite3/win/x64/sqlite3.lib )
    set(SqliteDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/sqlite3/win/x64/sqlite3.dll )
    set(GrpcLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/win/lib/*.lib )
    set(LuaLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/lua/win/lib/lua5.4.3-static.lib )
    set(ZipperLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zipper/libzip/win/staticZipper.lib )
    set(ZLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zlib/lib/win/zlibstatic.lib )
    set(ZlibDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/win/bin/zlib.dll )
    set(VCRUNTIME140DLL ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/win/bin/vcruntime140.dll )
    set(LIEFLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/LIEF.lib )
    set(LIEFDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/LIEF.dll )
    set(SSLLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libssl.lib )
    set(CryptoLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libcrypto.lib )
    set(SSLDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libssl-1_1-x64.dll )
    set(CryptoDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libcrypto-1_1-x64.dll )
    set(BoostFileSystemLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x64/static/libboost_filesystem-vc142-mt-s-x64-1_75.lib )

    function(GenerateUtil)
        foreach(var_name ${ARGV})
            set (${var_name} ON)
        endforeach()
        GenerateWindowsUtil()
        GenerateGeneralUtil()

        list(APPEND WINDOWS_UTIL_INCLUDE_DIRS   ${THIS_CMAKE_DIR} ${THIS_CMAKE_DIR}/General/ThirdParty ${THIS_CMAKE_DIR}/General/ThirdParty/boost_1_75_0)
        list(APPEND WINDOWS_UTIL_LIB_FILES      ${BoostFileSystemLib})
        set(GENERAL_UTIL_FILES ${GENERAL_UTIL_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_FILES ${WINDOWS_UTIL_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_LIB_FILES ${WINDOWS_UTIL_LIB_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_DLL_FILES ${WINDOWS_UTIL_DLL_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_INCLUDE_DIRS ${WINDOWS_UTIL_INCLUDE_DIRS} PARENT_SCOPE)

        message(STATUS "WINDOWS_UTIL_LIB_FILES: ${WINDOWS_UTIL_LIB_FILES}")
        message(STATUS "WINDOWS_UTIL_DLL_FILES: ${WINDOWS_UTIL_DLL_FILES}")
        message(STATUS "WINDOWS_UTIL_INCLUDE_DIRS: ${WINDOWS_UTIL_INCLUDE_DIRS}")
    endfunction()

elseif(APPLE)
    include(${CMAKE_CURRENT_LIST_DIR}/MacFeatures.cmake)
    
    set(CurlDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libcurl.4.dylib)
    set(CurlLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libcurl.a)
    set(SSLDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libssl.1.1.dylib)
    set(CryptoDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libcrypto.1.1.dylib)
    set(LibconfigDll
         ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/mac/universal/libconfig++.1.7.3.dylib)
    set(Sqlite3Dll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/sqlite3/mac/universal/libsqlite.dylib)
    set(BoostFileSystemLib
         ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/mac/universal/libboost_filesystem.a)
    set(LibPcapLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libpcap/libpcap/lib/mac/libpcap.a)
    set(LuaLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/lua/mac/universal/lib/libLua-5.4.3_static.a)
    set(ZipperLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zipper/libzip/mac/universal/libZipper.a)
    set(ZLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zlib/lib/mac/libz.a)
    file(GLOB GrpcLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/mac/universal/lib/*.a)

    function(GenerateUtil)
        GenerateMacOSUtil()
        set(MACOS_UTIL_FILES ${MACOS_UTIL_FILES} PARENT_SCOPE)
        GenerateGeneralUtil()
        set(GENERAL_UTIL_FILES ${GENERAL_UTIL_FILES} PARENT_SCOPE)
    endfunction()
endif()
