include(${CMAKE_CURRENT_LIST_DIR}/GeneralFeatures.cmake)

set(THIS_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR})
if(WIN32)
    include(${CMAKE_CURRENT_LIST_DIR}/WinFeatures.cmake)
    
    if(BUILD_TYPE STREQUAL "Release")
        set(LibconfigLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Release/libconfig++.lib )
        set(LibconfigDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Release/libconfig++.dll )
    else()
        set(LibconfigLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Debug/libconfig++.lib )
        set(LibconfigDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/win/x64/Debug/libconfig++.dll )
    endif()

    set(CurlLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/win/x64/libcurl.lib )
    set(CurlDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/win/x64/libcurl.dll )
    set(SqliteLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/sqlite3/win/x64/sqlite3.lib )
    set(SqliteDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/sqlite3/win/x64/sqlite3.dll )
    set(GrpcLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/win/lib/*.lib )
    set(LuaLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/lua/win/lib/lua5.4.3-static.lib )
    set(ZipperLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zipper/libzip/win/staticZipper.lib )
    set(ZLibLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zlib/lib/win/zlibstatic.lib )
    set(ZlibDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/win/bin/zlib.dll )
    set(VCRUNTIME140DLL ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/win/bin/vcruntime140.dll )
    set(LIEFLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/LIEF.lib )
    set(LIEFDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/LIEF.dll )
    set(SSLLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libssl.lib )
    set(CryptoLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libcrypto.lib )
    set(SSLDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libssl-1_1-x64.dll )
    set(CryptoDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/openssl/win/dynamic/libcrypto-1_1-x64.dll )
    set(AssimpLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/assimp/win/assimp-vc143-mt.lib)
    set(AssimpDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/assimp/win/assimp-vc143-mt.dll)
    set(InterceptionLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/interception/library/x64/interception.lib)
    set(InterceptionDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/interception/library/x64/interception.dll)
    if(CMAKE_VS_PLATFORM_NAME STREQUAL "x64")
        set(DetoursLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/Detours/build/lib.X64/detours.lib)
        set(BoostFileSystemLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x64/static/libboost_filesystem-vc142-mt-s-x64-1_75.lib )
        set(BoostDateTimeLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x64/static/libboost_date_time-vc142-mt-s-x64-1_75.lib )
        set(BoostRegexLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x64/static/libboost_regex-vc142-mt-s-x64-1_75.lib )
        set(BoostLibs ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x64/static/*.lib )
        set(GHInjectorDll "${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/GHInjector/GH Injector - x64.dll")
        set(LIEFLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/x64/LIEF.lib)
        set(LIEFDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/x64/LIEF.dll)
        set(PythonAll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/python/python311/win/x64)
        set(PythonLib ${PythonAll}/libs/python311.lib)
        set(PythonDll ${PythonAll}/python311.dll)
        set(libgit2Lib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libgit2/build/win/x64/dynamic/git2.lib)
        set(libgit2Dll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libgit2/build/win/x64/dynamic/git2.dll)
        
    elseif(CMAKE_VS_PLATFORM_NAME STREQUAL "Win32")
        set(DetoursLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/Detours/build/lib.X86/detours.lib)
        set(BoostFileSystemLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x86/static/libboost_filesystem-vc142-mt-s-x32-1_75.lib )
        set(BoostDateTimeLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x86/static/libboost_date_time-vc142-mt-s-x32-1_75.lib )
        set(BoostRegexLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x86/static/libboost_regex-vc142-mt-s-x32-1_75.lib )
        set(BoostLibs ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/win/x86/static/*.lib )
        set(GHInjectorDll "${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/GHInjector/GH Injector - x86.dll")
        set(LIEFLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/x86/LIEF.lib)
        set(LIEFDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/LIEF/win/lib/x86/LIEF.dll)
        set(PythonAll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/python/python311/win/x86)
        set(PythonLib ${PythonAll}/libs/python311.lib)
        set(PythonDll ${PythonAll}/python311.dll)
    endif()
    function(GenerateUtil)
        foreach(var_name ${ARGV})
            set (${var_name} ON)
        endforeach()
        GenerateWindowsUtil()
        GenerateGeneralUtil()

        list(APPEND WINDOWS_UTIL_INCLUDE_DIRS   ${THIS_CMAKE_DIR} ${THIS_CMAKE_DIR}/General/ThirdParty ${THIS_CMAKE_DIR}/General/ThirdParty/boost_1_75_0)
        list(APPEND WINDOWS_UTIL_LIB_FILES      ${BoostFileSystemLib} ${BoostDateTimeLib} ${BoostRegexLib})
        set(GENERAL_UTIL_FILES ${GENERAL_UTIL_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_FILES ${WINDOWS_UTIL_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_LIB_FILES ${WINDOWS_UTIL_LIB_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_DLL_FILES ${WINDOWS_UTIL_DLL_FILES} PARENT_SCOPE)
        set(WINDOWS_UTIL_INCLUDE_DIRS ${WINDOWS_UTIL_INCLUDE_DIRS} PARENT_SCOPE)

        message(STATUS "WINDOWS_UTIL_LIB_FILES: ${WINDOWS_UTIL_LIB_FILES}")
        message(STATUS "WINDOWS_UTIL_DLL_FILES: ${WINDOWS_UTIL_DLL_FILES}")
        message(STATUS "WINDOWS_UTIL_INCLUDE_DIRS: ${WINDOWS_UTIL_INCLUDE_DIRS}")
    endfunction()

    function(ClientDevLibFinalize)
        foreach(_file ${WINDOWS_UTIL_DLL_FILES})
            message(STATUS "Copying ${_file} to ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}")
            # if the folder name equals to ${THIS_CMAKE_DIR}/General/ThirdParty/python/**/win/x86. rename the destination folder to pythonlib
            if(${_file} MATCHES ".*General/ThirdParty/python/.*win/x86$")
                # if the folder exists, remove it
                if(EXISTS ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/pythonlib)
                    file(REMOVE_RECURSE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/pythonlib)
                endif()
                file(COPY ${_file} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO})
                # rename the folder to pythonlib
                file(RENAME ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/x86 ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/pythonlib)
            elseif(${_file} MATCHES ".*General/ThirdParty/python/.*win/x64$")
                if(EXISTS ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/pythonlib)
                    file(REMOVE_RECURSE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/pythonlib)
                endif()
                file(COPY ${_file} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO})
                # rename the folder to pythonlib
                file(RENAME ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/x64 ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO}/pythonlib)
            else()
                file(COPY ${_file} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO})
            endif()
        endforeach()

        if (${FEATURE_OLLVM})
            execute_process(
                COMMAND python ${CMAKE_CURRENT_LIST_DIR}/Scripts/ollvm_config.py ${CMAKE_BINARY_DIR}
            )
	    endif()
    endfunction()
elseif(APPLE)
    include(${CMAKE_CURRENT_LIST_DIR}/MacFeatures.cmake)
    
    set(CurlDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libcurl.4.dylib)
    set(CurlLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libcurl.a)
    set(SSLDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libssl.1.1.dylib)
    set(CryptoDll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/curl/mac/universal/libcrypto.1.1.dylib)
    set(LibconfigDll
         ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libconfig/mac/universal/libconfig++.1.7.3.dylib)
    set(Sqlite3Dll ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/sqlite3/mac/universal/libsqlite.dylib)
    set(BoostFileSystemLib
         ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/boost_1_75_0/lib/mac/universal/libboost_filesystem.a)
    set(LibPcapLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/libpcap/libpcap/lib/mac/libpcap.a)
    set(LuaLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/lua/mac/universal/lib/libLua-5.4.3_static.a)
    set(ZipperLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zipper/libzip/mac/universal/libZipper.a)
    set(ZLibLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/zlib/lib/mac/libz.a)
    file(GLOB GrpcLib ${CMAKE_CURRENT_LIST_DIR}/General/ThirdParty/grpc/mac/universal/lib/*.a)

    function(GenerateUtil)
        foreach(var_name ${ARGV})
            set (${var_name} ON)
        endforeach()
        GenerateMacOSUtil()
        GenerateGeneralUtil()

        list(APPEND MACOS_UTIL_INCLUDE_DIRS   ${THIS_CMAKE_DIR} ${THIS_CMAKE_DIR}/General/ThirdParty ${THIS_CMAKE_DIR}/General/ThirdParty/boost_1_75_0)
        list(APPEND MACOS_UTIL_LIB_FILES      ${BoostFileSystemLib})

        set(GENERAL_UTIL_FILES ${GENERAL_UTIL_FILES} PARENT_SCOPE)
        set(MACOS_UTIL_FILES ${MACOS_UTIL_FILES} PARENT_SCOPE)
        set(MACOS_UTIL_LIB_FILES ${MACOS_UTIL_LIB_FILES} PARENT_SCOPE)
        set(MACOS_UTIL_DLL_FILES ${MACOS_UTIL_DLL_FILES} PARENT_SCOPE)
        set(MACOS_UTIL_INCLUDE_DIRS ${MACOS_UTIL_INCLUDE_DIRS} PARENT_SCOPE)

        message(STATUS "MACOS_UTIL_LIB_FILES: ${MACOS_UTIL_LIB_FILES}")
        message(STATUS "MACOS_UTIL_DLL_FILES: ${MACOS_UTIL_DLL_FILES}")
        message(STATUS "MACOS_UTIL_INCLUDE_DIRS: ${MACOS_UTIL_INCLUDE_DIRS}")
    endfunction()
    function(ClientDevLibFinalize)
        foreach(dll ${MACOS_UTIL_DLL_FILES})
          file(COPY ${dll} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO})
        endforeach()
    endfunction()
endif()

